#!/bin/bash

# This script is used to release the package

## Constants

BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

printf "${BLUE}@jdw/jst release script${NC}\n\n"
sleep 1

## Sanity checks

printf "${CYAN}RUNNING TESTS${NC}\n"
yarn test

printf "\n${CYAN}BUILD DISTRIBUTION${NC}\n"
yarn build

printf "\n${CYAN}TEST DISTRIBUTION${NC}\n"
yarn test:dist

printf "\n${CYAN}PUBLISH${NC}\n"
cd dist
npm publish





